# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('processor', models.CharField(max_length=48)),
                ('free_ide', models.CharField(max_length=48)),
                ('community_openness', models.DecimalField(decimal_places=1, max_digits=2)),
                ('entry_threshold', models.IntegerField()),
                ('power', models.DecimalField(decimal_places=1, max_digits=3)),
                ('analog_port', models.IntegerField()),
                ('digital_port', models.IntegerField()),
                ('width', models.DecimalField(decimal_places=1, max_digits=3)),
                ('length', models.DecimalField(decimal_places=1, max_digits=3)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='prog_lang', to='boards.Languages'),
        ),
    ]
