# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='free_ide',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
