# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20171101_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='free_ide',
        ),
        migrations.AddField(
            model_name='board',
            name='free_ide',
            field=models.ManyToManyField(blank=True, to='boards.IDE'),
        ),
        migrations.AlterField(
            model_name='board',
            name='processor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Processor'),
        ),
        migrations.AlterField(
            model_name='board',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, to='boards.Languages'),
        ),
    ]
