# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('slug', models.SlugField(blank=True, max_length=48, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.Category'),
        ),
        migrations.AlterIndexTogether(
            name='board',
            index_together=set([('id', 'slug')]),
        ),
    ]
