# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20171108_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=48),
        ),
    ]
