# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20171108_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='community_openness',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='board',
            name='entry_threshold',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='board',
            name='length',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='board',
            name='width',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3),
        ),
    ]
