# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20171216_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
    ]
