# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20171217_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('id',)},
        ),
    ]
